--
-- Database
--

CREATE ROLE "DevicesUser" WITH LOGIN ENCRYPTED PASSWORD $$DevicesUserPassword$$;
CREATE DATABASE "Devices.Data";
ALTER DATABASE "Devices.Data" OWNER TO "DevicesUser";

--
-- Schemas
--

CREATE SCHEMA "Garden";

--
-- Tables
--

CREATE TABLE "Application" (
	"ApplicationID" int NOT NULL,
	"ApplicationName" varchar(1024) NOT NULL,
	"ApplicationActive" boolean NOT NULL,
	CONSTRAINT "PK_Application" PRIMARY KEY ("ApplicationID"),
	CONSTRAINT "IX_Application_ApplicationName" UNIQUE ("ApplicationName")
);

CREATE TABLE "Action" (
	"ActionID" int NOT NULL,
	"ActionType" int NOT NULL,
	"ActionParameters" varchar(1024) NOT NULL,
	"ActionArguments" varchar(1024) NULL,
	CONSTRAINT "PK_Action" PRIMARY KEY ("ActionID")
);

CREATE TABLE "Release" (
	"ReleaseID" int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"Date" timestamp with time zone NOT NULL,
	"ApplicationID" int NOT NULL,
	"Package" varchar(1024) NOT NULL,
	"PackageHash" varchar(64) NULL,
	"Version" varchar(64) NOT NULL,
	"ActionID" int NOT NULL,
	"ReleaseActive" boolean NOT NULL,
	CONSTRAINT "PK_Release" PRIMARY KEY ("ReleaseID"),
	CONSTRAINT "FK_Release_Application" FOREIGN KEY ("ApplicationID") REFERENCES "Application" ("ApplicationID"),
	CONSTRAINT "FK_Release_Action" FOREIGN KEY ("ActionID") REFERENCES "Action" ("ActionID")
);

CREATE TABLE "Device" (
	"DeviceID" varchar(64) NOT NULL,
	"DeviceName" varchar(1024) NOT NULL,
	"DeviceActive" boolean NOT NULL,
	CONSTRAINT "PK_Device" PRIMARY KEY ("DeviceID"),
	CONSTRAINT "IX_Device_DeviceName" UNIQUE ("DeviceName")
);

CREATE TABLE "DeviceFingerprint" (
	"FingerprintType" int NOT NULL,
	"FingerprintValue" varchar(1024) NOT NULL,
	"DeviceID" varchar(64) NOT NULL,
	CONSTRAINT "PK_DeviceFingerprint" PRIMARY KEY ("FingerprintType", "FingerprintValue"),
	CONSTRAINT "FK_DeviceFingerprint_Device" FOREIGN KEY ("DeviceID") REFERENCES "Device" ("DeviceID")
);

CREATE TABLE "DeviceMetric" (
	"DeviceID" varchar(64) NOT NULL,
	"Date" timestamp with time zone NOT NULL,
	"LastReboot" timestamp with time zone NOT NULL,
	"CpuUser" real NOT NULL,
	"CpuSystem" real NOT NULL,
	"CpuIdle" real NOT NULL,
	"MemoryTotal" int NOT NULL,
	"MemoryUsed" int NOT NULL,
	"MemoryFree" int NOT NULL,
	CONSTRAINT "PK_DeviceMetric" PRIMARY KEY ("DeviceID", "Date"),
	CONSTRAINT "FK_DeviceMetric_Device" FOREIGN KEY ("DeviceID") REFERENCES "Device" ("DeviceID")
);

CREATE TABLE "DeviceApplication" (
	"DeviceID" varchar(64) NOT NULL,
	"ApplicationID" int NOT NULL,
	CONSTRAINT "PK_DeviceApplication" PRIMARY KEY ("DeviceID", "ApplicationID"),
	CONSTRAINT "FK_DeviceApplication_Device" FOREIGN KEY ("DeviceID") REFERENCES "Device" ("DeviceID"),
	CONSTRAINT "FK_DeviceApplication_Application" FOREIGN KEY ("ApplicationID") REFERENCES "Application" ("ApplicationID")
);

CREATE TABLE "DeviceDeployment" (
	"DeploymentID" int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"DeviceID" varchar(64) NOT NULL,
	"ReleaseID" int NOT NULL,
	"Date" timestamp with time zone NOT NULL,
	"Success" boolean NOT NULL,
	"Details" text NULL,
	CONSTRAINT "PK_DeviceDeployment" PRIMARY KEY ("DeploymentID"),
	CONSTRAINT "IX_DeviceDeployment_DeviceIDReleaseID" UNIQUE ("DeviceID", "ReleaseID"),
	CONSTRAINT "FK_DeviceDeployment_Device" FOREIGN KEY ("DeviceID") REFERENCES "Device" ("DeviceID"),
	CONSTRAINT "FK_DeviceDeployment_Release" FOREIGN KEY ("ReleaseID") REFERENCES "Release" ("ReleaseID")
);

CREATE TABLE "User" (
	"UserID" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"Username" varchar(128) NOT NULL,
	"Password" varchar(128) NOT NULL,
	"FullName" varchar(128) NOT NULL,
	"Email" varchar(128) NOT NULL,
	"Role" varchar(128) NOT NULL,
	"Enabled" boolean NOT NULL,
	CONSTRAINT "PK_User" PRIMARY KEY ("UserID"),
	CONSTRAINT "IX_User_Username" UNIQUE ("Username")
);

CREATE TABLE "Garden"."WeatherCondition" (
	"DeviceID" varchar(64) NOT NULL,
	"Date" timestamp with time zone NOT NULL,
	"Temperature" numeric NOT NULL,
	"Humidity" numeric NOT NULL,
	"Pressure" numeric NOT NULL,
	"Illuminance" numeric NOT NULL,
	CONSTRAINT "PK_WeatherCondition" PRIMARY KEY ("DeviceID", "Date"),
	CONSTRAINT "FK_WeatherCondition_Device" FOREIGN KEY ("DeviceID") REFERENCES "Device" ("DeviceID")
);