name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Checkout Solution
      uses: actions/checkout@v4
    - name: Restore Dependencies
      run: dotnet restore ./Sources/Devices.sln
    - name: Build Solution
      run: dotnet build --no-restore ./Sources/Devices.sln
    - name: Test Solution
      run: dotnet test --no-build --verbosity normal ./Sources/Devices.sln
